const i18n = {
  zh: {
    siteTitle: "杨琪勇 - 个人主页",
    "nav.brand": "杨琪勇",
    "nav.basic": "基本信息",
    "nav.papers": "学术经历",
    "nav.lang": "外语&荣誉",
    "nav.awards": "获奖荣誉",
    "nav.intern": "实习&交换",
    name: "杨琪勇",
    school: "东华大学",
    period: "2023 - 2027",
    major: "信息管理与信息系统",
    "basic.title": "基础信息",
    "label.name": "姓名：",
    "label.school": "学校：",
    "label.period": "时间：",
    "label.major": "专业：",
    "label.email": "邮箱：",
    "papers.title": "学术经历",
    "label.journal": "期刊：",
    "label.date": "发表时间：",
    "label.link": "链接：",
    "paper1.title": "Assessing the Sustainable Development of the Tourism Industry Based on Fuzzy AHP and Grey Relational TOPSIS",
    "paper1.abstract": "针对旅游可持续发展评价中指标模糊性、权重分配主观性问题，构建涵盖经济、社会、环境、文化4个一级维度、13个二级指标的评价体系（含7个正向指标、6个负向指标），区分旅游发展的效益与风险。方法上，创新融合模糊层次分析法（FAHP）与灰色关联TOPSIS（GR-TOPSIS），通过三角模糊判断矩阵与一致性检验确定指标权重，整合欧氏距离与灰色关联度构建混合贴近度指数，提升模糊数据处理能力。以7个典型旅游区域为案例验证，得出旅游收入贡献权重最高、游客文化尊重度权重最低的关键结论；丽江清水可持续发展水平最优。通过敏感性分析，模型结论与熵权TOPSIS验证结果一致性显著。",
    "paper2.title": "Sustainable Evaluation Framework for Urban Creative Space: Exploring a Better Way for Urban Development",
    "paper2.abstract": "聚焦全球数字化与文化多样性背景下城市创意空间评价缺口，构建包含AIGC技术融合、文化遗产保护、数字文化产业经济效益、生态协同与社会包容、治理政策支持的5个一级维度、20个二级指标的跨文化评价框架。采用直觉模糊层次分析法（IFAHP）确定指标权重，结合TOPSIS对伦敦、上海等5个国际城市进行排名，伦敦综合可持续性居首（贴近度0.6623），上海位列第二（贴近度0.5282）。通过±20%权重扰动验证模型稳健性，70%的场景秩相关系数≥1.0。",
    "paper3.title": "Supply and Demand Prediction Analysis of Urban Gas Energy in China: A New Method Using GM-Markov-WOA",
    "paper3.abstract": "运用数学建模方法开展城市不可再生能源供需量预测。基于传统灰色模型GM(1,1)，加入马尔可夫链进行预测残差修正，并引入鲸群算法（WOA）优化马尔可夫链参数。覆盖天然气、人工煤气、液化石油气3类能源，处理2013-2023年历史数据并预判2024-2026年趋势。设置10次取平均值，通过留一法检验，结果显示WOA的引入使六组数据预测误差RMSE下降3.6%-9.9%，且结果略优于PSO。",
    "paper3.status": "返修后重新提交",
    "paper4.title": "Research on Accurate Prediction of Small-Sample Nonlinear Sequences in Multiple Scenarios（农产品冷链物流方向）",
    "paper4.abstract": "基于GM(1,N)+马尔可夫链+改进万有引力算法（IGSA），解决小样本非线性冷链物流序列预测难题。聚焦农产品冷链物流，选取第一产业增加值、第三产业从业人数等5个关键指标，构建GM(1,N)模型。结果MAPE仅10.23%，较传统GM(1,N)的54.65%大幅降低，预测2024年运输量达6.29亿吨，年增长率稳定在22%-23%。",
    "paper4.status": "初审中，外审",
    "none": "无",
    "lang.title": "外语水平与荣誉证明",
    "lang.cet": "大学英语",
    "lang.etc": "国才考试",
    "lang.etc.primary": "初级优秀",
    "lang.etc.mid": "中级良好",
    "lang.certs": "相关证书",
    "lang.tencent1": "腾讯产品经理训练营（入门）",
    "lang.tencent2": "腾讯产品经理训练营（进阶）",
    "lang.fullstack": "鼎捷校园全栈开发工程师",
    "lang.honors": "荣誉称号",
    "lang.honor1": "2023-2024 东华大学校一等奖学金",
    "lang.honor2": "2024-2025 东华大学天骥一等奖学金",
    "awards.title": "获奖荣誉",
    "label.prize": "奖项：",
    "award1.title": "2025年全国大学生数学竞赛（CMC）",
    "award1.prize": "非数学类B组省一等奖",
    "award1.desc": "数学学科基础竞赛，经过东华大学初赛（二等奖）",
    "award2.title": "2025年全国大学生英语竞赛（NECCS）",
    "award2.prize": "全国二等奖",
    "award2.desc": "英语学科基础竞赛",
    "award3.title": "2025年美国大学生数学建模竞赛（MCM/ICM）- B题",
    "award3.prize": "Honorable Mention",
    "award3.desc": "独立参加。针对「可持续旅游行业」议题，构建多目标决策模型（MCDM），引入模拟退火算法求解资源分配与环境保护的平衡解，为后续旅游业评价论文提供了初步的研究方向与方法启蒙。",
    "award4.title": "2024年亚太杯数学建模竞赛（APMCM）- C题",
    "award4.prize": "二等奖",
    "award4.desc": "独立参加。针对宠物行业规模进行预测，通过数据分析提出相关政策提议，以及研究宠物行业规模对于经济发展的影响，赛题属于政策建模。",
    "award5.title": "MathorCup高校数学建模挑战赛 - D题",
    "award5.prize": "省级三等奖",
    "award5.desc": "独立参加。选择声音降噪处理的赛题，学习音频波段相关的知识，将音频文件波幅可视化，并在人工智能协助下设计降噪算法，学习相关知识完成赛题。",
    "award6.title": "全国大学生计算机设计大赛",
    "award6.status": "作品审核中",
    "award6.desc": "团队协作完成红色精神文旅网站搭建，覆盖前端、后端开发。",
    "award7.title": "2026年美国大学生数学建模竞赛（MCM/ICM）- F题",
    "award7.status": "待公布",
    "award7.desc": "独立完成。聚焦AI与教育建模，构建不同专业求职竞争力评价模型，完成2026-2040年15年动力系统演化预测。",
    "award8.title": "2024年全国大学生创新创业大赛",
    "award8.prize": "省级立项并结项",
    "award8.desc": "参与/主持两项大学生创新创业大赛乡村振兴赛道项目，一项关于乡村养老体系评价（熵权-TOPSIS获取评价优劣性排序），另一项关于乡村经济发展短期预测模型（灰色预测，线下实地考察并设计调研访谈）。负责访谈、报告撰写、建模与数据分析可视化。",
    "intern.title": "实习及交换",
    "intern.vw": "上海大众汽车有限公司（Shanghai-Volkswagen）",
    "intern.vw.desc": "深度参与企业ESG品牌可持续建设项目，协助完成上汽大众与伊利牛奶ESG联动宣传。负责舆情监测，利用Python爬取五大社交平台400+评论进行情感分析与品牌形象差异调研，利用Tableau搭建传播热度可视化看板，支撑ESG传播决策。",
    "intern.ox": "牛津大学伍斯特学院暑期课程（Worcester College, Ox.）",
    "intern.ox.desc": "系统学习商业管理、数字营销与企业商业发展案例，结合华为、小米等中国企业完成4次商业实践案例汇报，提升跨文化学术与案例研究能力。"
  },
  en: {
    siteTitle: "Qiyong Yang - Personal Homepage",
    "nav.brand": "Qiyong Yang",
    "nav.basic": "Basic Info",
    "nav.papers": "Research",
    "nav.lang": "Languages & Honors",
    "nav.awards": "Awards",
    "nav.intern": "Internship & Exchange",
    name: "Qiyong Yang",
    school: "Donghua University",
    period: "2023 - 2027",
    major: "Information Management and Information Systems",
    "basic.title": "Basic Information",
    "label.name": "Name: ",
    "label.school": "University: ",
    "label.period": "Period: ",
    "label.major": "Major: ",
    "label.email": "Email: ",
    "papers.title": "Academic Experience",
    "label.journal": "Journal: ",
    "label.date": "Date: ",
    "label.link": "Link: ",
    "paper1.title": "Assessing the Sustainable Development of the Tourism Industry Based on Fuzzy AHP and Grey Relational TOPSIS",
    "paper1.abstract": "To address the subjectivity in weight allocation and indicator fuzziness in sustainable tourism evaluation, this study constructed an evaluation system covering four primary dimensions (economy, society, environment, culture) and 13 secondary indicators (7 positive, 6 negative). The approach innovatively integrates Fuzzy AHP and Grey Relational TOPSIS (GR-TOPSIS), using triangular fuzzy judgment matrices and consistency tests to determine weights, and combining Euclidean distance with grey relational degree to build a hybrid closeness index. Validated with seven typical tourism regions, the results show tourism revenue contributes the highest weight (0.189) and cultural respect the lowest (0.015); Lijiang Qingshui (eco-cultural type) achieved the highest sustainability level (closeness 0.693). Sensitivity analysis confirmed strong consistency with entropy-weight TOPSIS results.",
    "paper2.title": "Sustainable Evaluation Framework for Urban Creative Space: Exploring a Better Way for Urban Development",
    "paper2.abstract": "Focusing on the evaluation gap of urban creative spaces under the dual context of global digitalization and cultural diversity, this study constructs a cross-cultural evaluation framework with five primary dimensions (AIGC technology integration, cultural heritage protection, digital cultural industry economic benefits, ecological synergy & social inclusion, governance policy support) and 20 secondary indicators. Intuitionistic Fuzzy AHP (IFAHP) is used to determine weights, and TOPSIS ranks five international cities including London and Shanghai. London ranks highest (closeness 0.6623), Shanghai second (0.5282). Robustness tests with ±20% weight perturbations show a rank correlation coefficient ≥1.0 in 70% of scenarios, verifying model stability.",
    "paper3.title": "Supply and Demand Prediction Analysis of Urban Gas Energy in China: A New Method Using GM-Markov-WOA",
    "paper3.abstract": "This study applies mathematical modeling to predict urban non-renewable energy supply and demand. It enhances the traditional GM(1,1) grey model with a Markov chain for residual correction and Whale Optimization Algorithm (WOA) for parameter optimization. The study covers natural gas, manufactured gas, and LPG, processing 2013-2023 historical data and forecasting 2024-2026 trends. Using 10-run averaging and leave-one-out cross-validation, the results show WOA reduces RMSE by 3.6%–9.9% compared to traditional grey-Markov, and slightly outperforms PSO.",
    "paper3.status": "Revised and resubmitted",
    "paper4.title": "Research on Accurate Prediction of Small-Sample Nonlinear Sequences in Multiple Scenarios (Agricultural Cold Chain Logistics)",
    "paper4.abstract": "Aiming at small-sample, nonlinear prediction challenges in agricultural cold chain logistics, this study develops a GM(1,N) model combined with Markov chain and Improved Gravitational Search Algorithm (IGSA). Five key indicators (e.g., primary industry added value, tertiary industry employment) are used. The model achieves a MAPE of only 10.23%, significantly lower than the traditional GM(1,N) (54.65%), and predicts 2024 transport volume of 629 million tons with a stable annual growth rate of 22–23%.",
    "paper4.status": "Under review",
    "none": "N/A",
    "lang.title": "Language Proficiency & Honors",
    "lang.cet": "College English Test",
    "lang.etc": "ETIC (English Test for International Communication)",
    "lang.etc.primary": "Elementary Level - Excellent",
    "lang.etc.mid": "Intermediate Level - Good",
    "lang.certs": "Certificates",
    "lang.tencent1": "Tencent Product Manager Training (Introductory)",
    "lang.tencent2": "Tencent Product Manager Training (Advanced)",
    "lang.fullstack": "Dingjie Campus Full-Stack Developer",
    "lang.honors": "Honors",
    "lang.honor1": "2023-2024 Donghua University First-Class Scholarship",
    "lang.honor2": "2024-2025 Donghua University Tianji First-Class Scholarship",
    "awards.title": "Awards & Honors",
    "label.prize": "Prize: ",
    "award1.title": "2025 Chinese Mathematics Competitions (CMC)",
    "award1.prize": "Provincial First Prize (Non-Math Group B)",
    "award1.desc": "Basic mathematics competition, passed Donghua University preliminary (Second Prize).",
    "award2.title": "2025 National English Competition for College Students (NECCS)",
    "award2.prize": "National Second Prize",
    "award2.desc": "Basic English competition.",
    "award3.title": "2025 MCM/ICM (Problem B)",
    "award3.prize": "Honorable Mention",
    "award3.desc": "Solo participation. Built a multi-criteria decision-making model (MCDM) and introduced simulated annealing algorithm to balance resource allocation and environmental protection for sustainable tourism, providing initial direction for later tourism evaluation research.",
    "award4.title": "2024 Asia-Pacific Mathematical Contest in Modeling (APMCM) - Problem C",
    "award4.prize": "Second Prize",
    "award4.desc": "Solo participation. Predicted pet industry scale, proposed policy suggestions through data analysis, and studied the economic impact of the pet industry, under policy modeling.",
    "award5.title": "MathorCup Mathematical Modeling Challenge - Problem D",
    "award5.prize": "Provincial Third Prize",
    "award5.desc": "Solo participation. Selected audio denoising topic, studied audio waveband knowledge, visualized audio amplitudes, and designed a denoising algorithm with AI assistance.",
    "award6.title": "National College Computer Design Contest",
    "award6.status": "Under review",
    "award6.desc": "Team project: built a red-culture tourism website covering front-end and back-end development.",
    "award7.title": "2026 MCM/ICM - Problem F",
    "award7.status": "Pending announcement",
    "award7.desc": "Solo participation. Focused on AI and education modeling, constructed a career competitiveness evaluation model across different majors, and completed a 15-year dynamic system evolution prediction (2026-2040).",
    "award8.title": "2024 National College Student Innovation and Entrepreneurship Competition",
    "award8.prize": "Provincial-level Project Approval and Completion",
    "award8.desc": "Participated/led two rural revitalization track projects: one on rural elderly care system evaluation (Entropy-TOPSIS), another on short-term rural economic forecasting (Grey Prediction, with field investigation and interviews). Responsible for interviews, report writing, modeling, and data visualization.",
    "intern.title": "Internship & Exchange Programs",
    "intern.vw": "Shanghai Volkswagen Automotive Co., Ltd. (Shanghai-Volkswagen)",
    "intern.vw.desc": "Deeply involved in corporate ESG brand sustainability projects, assisted in VW & Yili Milk ESG joint promotion. Monitored public opinion by scraping 400+ comments from five social platforms with Python for sentiment analysis and brand image comparison. Built a communication heatmap dashboard with Tableau to support ESG communication decisions.",
    "intern.ox": "Worcester College, University of Oxford Summer Program",
    "intern.ox.desc": "Systematically studied business management, digital marketing, and corporate business development cases. Completed four business case reports incorporating Chinese enterprises like Huawei and Xiaomi, enhancing cross-cultural academic and case study abilities."
  }
};

let currentLang = 'zh';

function switchLang(lang) {
  currentLang = lang;
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang] && i18n[lang][key]) {
      el.textContent = i18n[lang][key];
    }
  });
  const btn = document.getElementById('lang-switch');
  if (btn) {
    btn.textContent = lang === 'zh' ? 'English' : '中文';
  }
}

document.addEventListener('DOMContentLoaded', () => {
  switchLang('zh');
  const btn = document.getElementById('lang-switch');
  if (btn) {
    btn.addEventListener('click', () => {
      const newLang = currentLang === 'zh' ? 'en' : 'zh';
      switchLang(newLang);
    });
  }
});